#!/usr/bin/env python3
"""
SOC Threat Detection Monitor
==============================
Portfolio Project — Cybersecurity Engineering

A Python-based Security Operations Center (SOC) log correlation engine
that ingests authentication logs, applies SIGMA-inspired detection rules,
scores threats, and generates prioritized analyst alerts.

Simulates core SOC analyst workflows:
  - Multi-source log ingestion
  - Pattern-based threat detection (brute-force, port scan, privilege escalation)
  - Alert severity scoring (Critical / High / Medium / Low)
  - IOC tracking (IP reputation, failed login counters)
  - Structured alert output for SIEM-style review

Usage:
    python soc_monitor.py --log path/to/auth.log [--rules rules.json] [--output alerts.json]
    python soc_monitor.py --demo   # Run with built-in synthetic log data

Author: Adil S R
Role Alignment: SOC Analyst, SIEM Analyst, Security Monitoring Analyst
"""

import json
import re
import sys
import time
import argparse
from dataclasses import dataclass, field, asdict
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Optional


# ─────────────────────────────────────────────────────────────────────────────
# Data Models
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class LogEvent:
    """Parsed log event from auth.log or syslog format."""
    raw: str
    timestamp: str
    hostname: str
    process: str
    message: str
    source_ip: Optional[str] = None
    username: Optional[str] = None
    event_type: str = "UNKNOWN"


@dataclass
class Alert:
    """Security alert generated by a detection rule match."""
    alert_id: str
    rule_name: str
    severity: str          # CRITICAL / HIGH / MEDIUM / LOW / INFO
    description: str
    source_ip: Optional[str]
    username: Optional[str]
    event_count: int
    first_seen: str
    last_seen: str
    raw_events: list[str] = field(default_factory=list)
    mitre_tactic: str = ""
    mitre_technique: str = ""
    recommended_action: str = ""

    def to_dict(self) -> dict:
        return asdict(self)


# ─────────────────────────────────────────────────────────────────────────────
# Log Parser
# ─────────────────────────────────────────────────────────────────────────────

# Common syslog line patterns
SYSLOG_PATTERN = re.compile(
    r"(?P<timestamp>\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2})\s+"
    r"(?P<hostname>\S+)\s+"
    r"(?P<process>\S+?)(?:\[\d+\])?:\s+"
    r"(?P<message>.+)"
)
IP_PATTERN = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
USER_FAILED_PATTERN = re.compile(
    r"(?:Invalid user|Failed password for(?: invalid user)?)\s+(\S+)"
)
USER_ACCEPTED_PATTERN = re.compile(r"Accepted \w+ for (\S+)")
PORT_SCAN_PATTERN = re.compile(r"refused connect from|Did not receive identification string")


def parse_log_line(raw_line: str) -> Optional[LogEvent]:
    """Parse a single syslog-format line into a LogEvent."""
    raw_line = raw_line.strip()
    if not raw_line:
        return None

    match = SYSLOG_PATTERN.match(raw_line)
    if not match:
        return None

    event = LogEvent(
        raw=raw_line,
        timestamp=match.group("timestamp"),
        hostname=match.group("hostname"),
        process=match.group("process"),
        message=match.group("message"),
    )

    # Extract source IP
    ips = IP_PATTERN.findall(event.message)
    if ips:
        # Filter out localhost
        non_local = [ip for ip in ips if not ip.startswith("127.")]
        event.source_ip = non_local[-1] if non_local else ips[0]

    # Classify event type and extract username
    msg = event.message
    if "Failed password" in msg or "Invalid user" in msg:
        event.event_type = "FAILED_LOGIN"
        m = USER_FAILED_PATTERN.search(msg)
        if m:
            event.username = m.group(1)
    elif "Accepted" in msg:
        event.event_type = "SUCCESSFUL_LOGIN"
        m = USER_ACCEPTED_PATTERN.search(msg)
        if m:
            event.username = m.group(1)
    elif "session opened" in msg.lower():
        event.event_type = "SESSION_OPEN"
    elif "session closed" in msg.lower():
        event.event_type = "SESSION_CLOSE"
    elif "refused connect" in msg.lower() or "Did not receive" in msg:
        event.event_type = "CONNECTION_REFUSED"
    elif "sudo" in event.process.lower():
        event.event_type = "SUDO"
    elif "COMMAND" in msg:
        event.event_type = "COMMAND_EXECUTION"
    elif "authentication failure" in msg.lower():
        event.event_type = "AUTH_FAILURE"

    return event


def parse_log_file(log_path: str) -> list[LogEvent]:
    """Parse all lines from a log file."""
    events = []
    with open(log_path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            event = parse_log_line(line)
            if event:
                events.append(event)
    return events


# ─────────────────────────────────────────────────────────────────────────────
# Detection Engine
# ─────────────────────────────────────────────────────────────────────────────

class DetectionEngine:
    """
    Applies SIGMA-inspired detection rules to parsed log events.

    Built-in rules:
      - SSH Brute Force (> threshold failed logins from same IP)
      - Password Spray (failed logins against many different users from one IP)
      - Successful Login after Brute Force (compromise indicator)
      - Port Scan Signature (multiple refused connections)
      - Privilege Escalation via Sudo
      - Root Login Attempt
    """

    def __init__(self, rules: Optional[dict] = None):
        self.rules = rules or self._default_rules()
        self._alerts: list[Alert] = []
        self._alert_counter = 0

        # Tracking state
        self._failed_by_ip: dict[str, list[LogEvent]] = defaultdict(list)
        self._failed_by_user: dict[str, list[LogEvent]] = defaultdict(list)
        self._users_by_ip: dict[str, set] = defaultdict(set)
        self._refused_by_ip: dict[str, int] = defaultdict(int)
        self._sudo_events: list[LogEvent] = []
        self._successful_after_fail: list[LogEvent] = []

    def _default_rules(self) -> dict:
        return {
            "brute_force_threshold": 5,
            "spray_threshold": 3,
            "refused_scan_threshold": 8,
        }

    def _new_alert_id(self) -> str:
        self._alert_counter += 1
        return f"ALERT-{self._alert_counter:04d}"

    def process_events(self, events: list[LogEvent]) -> list[Alert]:
        """Process all events and generate alerts."""
        for event in events:
            self._process_single(event)
        self._finalize()
        return self._alerts

    def _process_single(self, event: LogEvent) -> None:
        """Route a single event to relevant tracking buckets."""
        if event.event_type == "FAILED_LOGIN":
            if event.source_ip:
                self._failed_by_ip[event.source_ip].append(event)
            if event.username:
                self._failed_by_user[event.username].append(event)
            if event.source_ip and event.username:
                self._users_by_ip[event.source_ip].add(event.username)

        elif event.event_type == "SUCCESSFUL_LOGIN":
            if event.source_ip and event.source_ip in self._failed_by_ip:
                if len(self._failed_by_ip[event.source_ip]) >= 2:
                    self._successful_after_fail.append(event)

        elif event.event_type == "CONNECTION_REFUSED":
            if event.source_ip:
                self._refused_by_ip[event.source_ip] += 1

        elif event.event_type in ("SUDO", "COMMAND_EXECUTION"):
            self._sudo_events.append(event)

    def _finalize(self) -> None:
        """Evaluate accumulated state against detection thresholds."""
        bf_threshold = self.rules.get("brute_force_threshold", 5)
        spray_threshold = self.rules.get("spray_threshold", 3)
        scan_threshold = self.rules.get("refused_scan_threshold", 8)

        # ── Rule 1: SSH Brute Force ─────────────────────────────────────────
        for ip, evs in self._failed_by_ip.items():
            if len(evs) >= bf_threshold:
                self._alerts.append(Alert(
                    alert_id=self._new_alert_id(),
                    rule_name="SSH_BRUTE_FORCE",
                    severity="HIGH",
                    description=(
                        f"SSH brute-force attack detected from {ip}: "
                        f"{len(evs)} failed login attempts."
                    ),
                    source_ip=ip,
                    username=None,
                    event_count=len(evs),
                    first_seen=evs[0].timestamp,
                    last_seen=evs[-1].timestamp,
                    raw_events=[e.raw for e in evs[:5]],
                    mitre_tactic="Credential Access",
                    mitre_technique="T1110.001 - Brute Force: Password Guessing",
                    recommended_action=(
                        "Block IP at firewall. Review SSH auth logs. "
                        "Consider fail2ban deployment."
                    ),
                ))

        # ── Rule 2: Password Spray ──────────────────────────────────────────
        for ip, users in self._users_by_ip.items():
            if len(users) >= spray_threshold:
                evs = self._failed_by_ip[ip]
                self._alerts.append(Alert(
                    alert_id=self._new_alert_id(),
                    rule_name="PASSWORD_SPRAY",
                    severity="HIGH",
                    description=(
                        f"Password spray detected from {ip}: "
                        f"targeted {len(users)} unique usernames."
                    ),
                    source_ip=ip,
                    username=None,
                    event_count=len(evs),
                    first_seen=evs[0].timestamp if evs else "N/A",
                    last_seen=evs[-1].timestamp if evs else "N/A",
                    raw_events=[e.raw for e in evs[:5]],
                    mitre_tactic="Credential Access",
                    mitre_technique="T1110.003 - Brute Force: Password Spraying",
                    recommended_action=(
                        "Block source IP. Audit targeted accounts. "
                        "Enable account lockout policies."
                    ),
                ))

        # ── Rule 3: Successful Login after Failed Attempts ──────────────────
        for event in self._successful_after_fail:
            self._alerts.append(Alert(
                alert_id=self._new_alert_id(),
                rule_name="SUCCESSFUL_LOGIN_AFTER_BRUTE_FORCE",
                severity="CRITICAL",
                description=(
                    f"CRITICAL: Successful login from {event.source_ip} "
                    f"as '{event.username}' AFTER multiple failed attempts. "
                    f"Possible account compromise!"
                ),
                source_ip=event.source_ip,
                username=event.username,
                event_count=1,
                first_seen=event.timestamp,
                last_seen=event.timestamp,
                raw_events=[event.raw],
                mitre_tactic="Initial Access",
                mitre_technique="T1078 - Valid Accounts",
                recommended_action=(
                    "IMMEDIATE: Isolate session. Reset account credentials. "
                    "Initiate incident response. Preserve forensic artifacts."
                ),
            ))

        # ── Rule 4: Port Scan ───────────────────────────────────────────────
        for ip, count in self._refused_by_ip.items():
            if count >= scan_threshold:
                self._alerts.append(Alert(
                    alert_id=self._new_alert_id(),
                    rule_name="PORT_SCAN_DETECTED",
                    severity="MEDIUM",
                    description=(
                        f"Potential port scan from {ip}: "
                        f"{count} refused connection attempts."
                    ),
                    source_ip=ip,
                    username=None,
                    event_count=count,
                    first_seen="N/A",
                    last_seen="N/A",
                    raw_events=[],
                    mitre_tactic="Discovery",
                    mitre_technique="T1046 - Network Service Discovery",
                    recommended_action="Review IDS/IPS logs. Block scanning IP if confirmed.",
                ))

        # ── Rule 5: Sudo / Privilege Escalation ────────────────────────────
        if self._sudo_events:
            # Group by user
            by_user: dict[str, list] = defaultdict(list)
            for e in self._sudo_events:
                by_user[e.username or "unknown"].append(e)

            for user, evs in by_user.items():
                if len(evs) >= 3:
                    self._alerts.append(Alert(
                        alert_id=self._new_alert_id(),
                        rule_name="EXCESSIVE_SUDO_ACTIVITY",
                        severity="MEDIUM",
                        description=(
                            f"User '{user}' executed {len(evs)} privileged commands "
                            f"via sudo — possible privilege escalation or insider threat."
                        ),
                        source_ip=evs[0].source_ip,
                        username=user,
                        event_count=len(evs),
                        first_seen=evs[0].timestamp,
                        last_seen=evs[-1].timestamp,
                        raw_events=[e.raw for e in evs[:3]],
                        mitre_tactic="Privilege Escalation",
                        mitre_technique="T1548 - Abuse Elevation Control Mechanism",
                        recommended_action=(
                            "Review sudo command history. Verify authorization "
                            "for each command executed."
                        ),
                    ))

    @property
    def alerts(self) -> list[Alert]:
        return self._alerts


# ─────────────────────────────────────────────────────────────────────────────
# Reporting
# ─────────────────────────────────────────────────────────────────────────────

SEVERITY_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
SEVERITY_COLOR = {
    "CRITICAL": "[!!!]",
    "HIGH":     "[!! ]",
    "MEDIUM":   "[!  ]",
    "LOW":      "[   ]",
    "INFO":     "[INF]",
}


def print_report(alerts: list[Alert], event_count: int) -> None:
    """Pretty-print the SOC alert report to stdout."""
    sorted_alerts = sorted(alerts, key=lambda a: SEVERITY_ORDER.get(a.severity, 9))

    print("\n" + "=" * 70)
    print("           SOC THREAT DETECTION REPORT")
    print(f"           Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 70)
    print(f"  Events Analyzed : {event_count}")
    print(f"  Alerts Generated: {len(alerts)}")
    print(
        f"  Breakdown: "
        f"CRITICAL={sum(1 for a in alerts if a.severity=='CRITICAL')} | "
        f"HIGH={sum(1 for a in alerts if a.severity=='HIGH')} | "
        f"MEDIUM={sum(1 for a in alerts if a.severity=='MEDIUM')}"
    )
    print("-" * 70)

    for alert in sorted_alerts:
        icon = SEVERITY_COLOR.get(alert.severity, "⚪")
        icon = SEVERITY_COLOR.get(alert.severity, "[ ]")
        print(f"\n  {icon} [{alert.severity}] {alert.rule_name} -- {alert.alert_id}")
        print(f"     Description : {alert.description}")
        print(f"     Source IP   : {alert.source_ip or 'N/A'}")
        print(f"     Username    : {alert.username or 'N/A'}")
        print(f"     Event Count : {alert.event_count}")
        print(f"     Timeframe   : {alert.first_seen} -> {alert.last_seen}")
        print(f"     MITRE ATT&CK: {alert.mitre_technique}")
        print(f"     Action      : {alert.recommended_action}")

    print("\n" + "=" * 70)
    print("  END OF REPORT - Review CRITICAL and HIGH alerts immediately.")
    print("=" * 70 + "\n")


# ─────────────────────────────────────────────────────────────────────────────
# Demo mode — synthetic log data
# ─────────────────────────────────────────────────────────────────────────────

DEMO_LOG = """\
May 26 08:01:01 server1 sshd[1234]: Failed password for invalid user admin from 192.168.1.50 port 54321 ssh2
May 26 08:01:03 server1 sshd[1234]: Failed password for invalid user root from 192.168.1.50 port 54322 ssh2
May 26 08:01:05 server1 sshd[1234]: Failed password for invalid user ubuntu from 192.168.1.50 port 54323 ssh2
May 26 08:01:07 server1 sshd[1234]: Failed password for invalid user postgres from 192.168.1.50 port 54324 ssh2
May 26 08:01:09 server1 sshd[1234]: Failed password for invalid user pi from 192.168.1.50 port 54325 ssh2
May 26 08:01:11 server1 sshd[1234]: Failed password for invalid user oracle from 192.168.1.50 port 54326 ssh2
May 26 08:01:20 server1 sshd[1234]: Failed password for testuser from 10.0.0.99 port 22001 ssh2
May 26 08:01:21 server1 sshd[1234]: Failed password for testuser from 10.0.0.99 port 22002 ssh2
May 26 08:01:22 server1 sshd[1234]: Failed password for testuser from 10.0.0.99 port 22003 ssh2
May 26 08:01:23 server1 sshd[1234]: Failed password for testuser from 10.0.0.99 port 22004 ssh2
May 26 08:01:24 server1 sshd[1234]: Failed password for testuser from 10.0.0.99 port 22005 ssh2
May 26 08:02:00 server1 sshd[1234]: Accepted password for testuser from 10.0.0.99 port 22006 ssh2
May 26 08:02:05 server1 sshd[1234]: pam_unix(sshd:session): session opened for user testuser by (uid=0)
May 26 08:03:00 server1 sudo[2001]: testuser : TTY=pts/0 ; PWD=/home/testuser ; USER=root ; COMMAND=/bin/bash
May 26 08:03:10 server1 sudo[2001]: testuser : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/usr/bin/cat /etc/shadow
May 26 08:03:20 server1 sudo[2001]: testuser : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/bin/chmod 777 /etc/passwd
May 26 08:05:00 server1 sshd[1234]: refused connect from 172.16.0.77 (172.16.0.77)
May 26 08:05:01 server1 sshd[1234]: refused connect from 172.16.0.77 (172.16.0.77)
May 26 08:05:02 server1 sshd[1234]: refused connect from 172.16.0.77 (172.16.0.77)
May 26 08:05:03 server1 sshd[1234]: refused connect from 172.16.0.77 (172.16.0.77)
May 26 08:05:04 server1 sshd[1234]: refused connect from 172.16.0.77 (172.16.0.77)
May 26 08:05:05 server1 sshd[1234]: refused connect from 172.16.0.77 (172.16.0.77)
May 26 08:05:06 server1 sshd[1234]: refused connect from 172.16.0.77 (172.16.0.77)
May 26 08:05:07 server1 sshd[1234]: refused connect from 172.16.0.77 (172.16.0.77)
May 26 08:05:08 server1 sshd[1234]: refused connect from 172.16.0.77 (172.16.0.77)
May 26 08:06:00 server1 sshd[1234]: Failed password for invalid user spray_test1 from 10.10.10.5 port 55001 ssh2
May 26 08:06:01 server1 sshd[1234]: Failed password for invalid user spray_test2 from 10.10.10.5 port 55002 ssh2
May 26 08:06:02 server1 sshd[1234]: Failed password for invalid user spray_test3 from 10.10.10.5 port 55003 ssh2
May 26 08:06:03 server1 sshd[1234]: Failed password for invalid user spray_test4 from 10.10.10.5 port 55004 ssh2
"""


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="SOC Threat Detection Monitor",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python soc_monitor.py --demo
  python soc_monitor.py --log /var/log/auth.log
  python soc_monitor.py --log auth.log --output alerts.json
        """,
    )
    parser.add_argument("--log", help="Path to auth log file")
    parser.add_argument("--rules", help="Path to rules JSON file", default=None)
    parser.add_argument("--output", help="Save alerts to JSON file", default=None)
    parser.add_argument("--demo", action="store_true", help="Run with built-in demo data")
    args = parser.parse_args()

    rules = None
    if args.rules:
        with open(args.rules) as f:
            rules = json.load(f)

    if args.demo:
        print("[*] Running SOC Monitor in DEMO mode...")
        lines = DEMO_LOG.strip().split("\n")
        events = [parse_log_line(line) for line in lines]
        events = [e for e in events if e]
    elif args.log:
        log_path = Path(args.log)
        if not log_path.exists():
            print(f"[!] Log file not found: {log_path}")
            sys.exit(1)
        print(f"[*] Parsing log file: {log_path}")
        events = parse_log_file(str(log_path))
    else:
        parser.print_help()
        sys.exit(0)

    print(f"[+] Parsed {len(events)} log events.")
    engine = DetectionEngine(rules)
    alerts = engine.process_events(events)
    print(f"[+] Detection complete. {len(alerts)} alert(s) generated.")

    print_report(alerts, len(events))

    if args.output:
        output_path = Path(args.output)
        alert_data = [a.to_dict() for a in alerts]
        with open(output_path, "w") as f:
            json.dump(alert_data, f, indent=2)
        print(f"[+] Alerts saved to: {output_path}")


if __name__ == "__main__":
    main()
